[package]
name = "image_disector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap2 = "0.5.10"
rayon = "1.7.0"
serde = { version = "1.0.154", features = ["derive"] }
serde_json = "1.0.94"
tar = "0.4.38"
url = "2.3.1"
